"""add arxiv_papers table

Revision ID: 7faf8835aa4f
Revises: 833cf4d8ea5b
Create Date: 2026-03-11 18:30:01.331800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7faf8835aa4f'
down_revision: Union[str, Sequence[str], None] = '833cf4d8ea5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arxiv_papers',
    sa.Column('arxiv_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('authors', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('categories', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('arxiv_id')
    )
    op.drop_index(op.f('ix_papers_id'), table_name='papers')
    op.drop_table('papers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('openalex_id', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('authors', sa.VARCHAR(), nullable=False),
    sa.Column('abstract', sa.VARCHAR(), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('url', sa.VARCHAR(), nullable=True),
    sa.Column('open_access_pdf_url', sa.VARCHAR(), nullable=True),
    sa.Column('citation_count', sa.INTEGER(), nullable=False),
    sa.Column('tags', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('full_text', sa.VARCHAR(), nullable=True),
    sa.Column('summary', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openalex_id')
    )
    op.create_index(op.f('ix_papers_id'), 'papers', ['id'], unique=False)
    op.drop_table('arxiv_papers')
    # ### end Alembic commands ###
