"""Add full_text and summary columns to papers

Revision ID: a364be21935c
Revises: 0e37add4007d
Create Date: 2026-03-10 15:00:01.141916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a364be21935c'
down_revision: Union[str, Sequence[str], None] = '0e37add4007d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_sessions_id'), table_name='search_sessions')
    op.drop_table('search_sessions')
    op.add_column('papers', sa.Column('full_text', sa.String(), nullable=True))
    op.add_column('papers', sa.Column('summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'summary')
    op.drop_column('papers', 'full_text')
    op.create_table('search_sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('original_query', sa.VARCHAR(), nullable=False),
    sa.Column('topic_category', sa.VARCHAR(), nullable=True),
    sa.Column('refined_query', sa.VARCHAR(), nullable=True),
    sa.Column('result_count', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_sessions_id'), 'search_sessions', ['id'], unique=False)
    # ### end Alembic commands ###
